plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.sequenceiq'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.sequenceiq"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
